


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


set-option -g history-limit 10000000
set -s escape-time 0
setw -g aggressive-resize on

bind-key R respawn-pane -k \; display 'Respawned Pane!'

bind % split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'

#urxvt tab like window switching (-n: no prior escape seq)
bind k confirm kill-window
bind a last-window
bind space command-prompt -p index "select-window"
bind r source-file ~/.tmux.conf
bind-key g set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# powerline
set -g default-terminal "screen-256color"
#set -g default-terminal xterm-256color
#source-file ~/softs/powerline/powerline/bindings/tmux/powerline.conf
set-option -g status on
set-option -g status-interval 4
set-option -g status-justify "centre"
set-option -g status-left-length 40
set-option -g status-right-length 90
#set-option -g status-left "#(~/bin/powerline left)"
#set-option -g status-right "#(~/bin/powerline right)"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# set pane colors - highlight the active pane
#setw -g pane-border-status top
#setw -g pane-border-format '─'
#setw -g pane-border-fg colour8
#set -g pane-active-border-style fg=colour8
#set -g pane-active-border-style bg=default

## set inactive/active window styles
#set -g window-style 'fg=colour247,bg=colour236'
#set -g window-active-style 'fg=colour250,bg=234'

set-option -g set-clipboard on
# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

## to enable mouse scroll, see https://github.com/tmux/tmux/issues/145#issuecomment-150736967
##bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
#bind -T root MouseDown2Pane run -b "xclip -o | tmux load-buffer - && tmux paste-buffer -s ' '"
#bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -selection primary -i" \; display-message "highlighted selection copied to system clipboard xclip -selection pri"

# To copy, left click and drag to highlight text in yellow,
# once you release left click yellow text will disappear and will automatically be available in clibboard
setw -g mode-keys vi
# Vi copypaste mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection

set-option -g status-position top

set-option -g automatic-rename on
set-option -g allow-rename on
# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# fixes shift-pageup/shift-pagedown
#set -ga terminal-overrides 'xterm*:smcup@:rmcup@'
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
#bind -n Pageup copy-mode -u

#bind WheelUpPane   page-up
#bind -t vi-copy    WheelDownPane page-down

# Plugins
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-continuum'

#set -g @colors-solarized 'dark'

set -g @continuum-restore 'on'
run-shell ~/.tmux/plugins/tmux-yank/yank.tmux

# Sessions
bind s source-file ~/.tmux.conf

set-option -g default-command "/bin/bash"
set-option -g default-shell "/bin/bash"

# EOF
run '~/.tmux/plugins/tpm/tpm'
