


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


set-option -g history-limit 10000000
set -s escape-time 0
setw -g aggressive-resize on

bind-key R respawn-pane -k \; display 'Respawned Pane!'

bind % split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'

#urxvt tab like window switching (-n: no prior escape seq)
bind k confirm kill-window
bind a last-window
bind space command-prompt -p index "select-window"
bind r source-file ~/.tmux.conf
bind-key g set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# Solarized theme
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'
# powerline
set -g default-terminal "screen-256color"
source-file ~/softs/powerline/powerline/bindings/tmux/powerline.conf
set-option -g status-position top
#set-option -g status on
#set-option -g status-interval 4
#set-option -g status-justify "centre"
#set-option -g status-left-length 100
#set-option -g status-right-length 100
#set-option -g status-left "#(~/.local/bin/powerline left)"
#set-option -g status-right "#(~/.local/bin/powerline right)"
#set -g status-left "session: #S || window: #I || pane: #P"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
bind = select-layout even-horizontal

# set pane colors - highlight the active pane
#setw -g pane-border-status top
#setw -g pane-border-format '─'
#setw -g pane-border-fg colour8
#set -g pane-active-border-style fg=colour8
#set -g pane-active-border-style bg=default

bind -n S-Left  previous-window
bind -n S-Right next-window

## set inactive/active window styles
#set -g window-style 'fg=colour247,bg=colour236'
#set -g window-active-style 'fg=colour250,bg=234'

set-option -g set-clipboard on
# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Sane scrolling
# fixes shift-pageup/shift-pagedown
set -ga terminal-overrides 'xterm*:smcup@:rmcup@'
set -ga terminal-override ',rxvt-uni*:XT:Ms=\E]52;%p1%s;%p2%s\007'
set-window-option -g xterm-keys on

# To copy, left click and drag to highlight text in yellow,
# once you release left click yellow text will disappear and will automatically be available in clibboard
setw -g mode-keys vi
## Vi copypaste mode
#bind-key -T copy-mode-vi v send -X begin-selection
#bind-key -T copy-mode-vi y send -X copy-selection


set-option -g automatic-rename off
set-option -g allow-rename on
# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

set -g focus-events

#bind WheelUpPane   page-up
#bind -t vi-copy    WheelDownPane page-down

set -g @yank_selection 'primary' # or 'secondary' or 'clipboard'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#set -g @colors-solarized 'dark'

set -g @continuum-restore 'on'
#run-shell ~/.tmux/plugins/tmux-yank/yank.tmux

# Sessions
bind s source-file ~/.tmux.conf

set-option -g default-command "/bin/bash"
set-option -g default-shell "/bin/bash"

run-shell "powerline-daemon -q"

# EOF
run '~/.tmux/plugins/tpm/tpm'
