


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


set-option -g history-limit 10000000
set -s escape-time 0

bind % split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# Enable mouse control (clickable windows, panes, resizable panes)
#set -g mouse-select-window on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

## to enable mouse scroll, see https://github.com/tmux/tmux/issues/145#issuecomment-150736967
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind -T root MouseDown2Pane run -b "xclip -o | tmux load-buffer - && tmux paste-buffer -s ' '"
#
# Vi copypaste
setw -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection primary -i" \; display-message "highlighted selection copied to system clipboard xclip -selection pri"
#
#bind-key '!' copy-mode

# Drag to re-order windows
bind-key -n MouseDrag1Status swap-window -t=


#urxvt tab like window switching (-n: no prior escape seq)
bind -n C-t new-window -c '#{pane_current_path}'
bind -n C-q confirm-before -p "kill-window #W? (y/n)" kill-window
bind -n S-left prev
bind -n S-right next

set-option -g automatic-rename off
set-option -g allow-rename off
# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# Sessions
bind s source-file ~/.tmux.conf

set -g @colors-solarized 'dark'

set-option -g default-command "/bin/bash"

# EOF
run '~/.tmux/plugins/tpm/tpm'
